name: Publish Library

on:
  push:
    tags:
      - "v*.*.*"   # publish khi cรณ tag v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build core-lib

      - name: Publish to GitHub Packages
        run: |
          cd dist/core-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
